general_settings:
  name: tts_app
  display_name: TTS Kokoro
  description: A simple application template. Able to display applications with ImGui and ImPlot
  logo_path: assets/images/logo.png
  project_version: 1 0 0
  long_startup_process: true
